### ISSUE TITLE
Error on Ruby 3.0

### ISSUE THREAD

**Issue by rbclark** [GoogleCloudPlatform/inspec-gcp-helpers#12]
I am attempting to run the [inspec-gcp-cis-benchmark](https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark) profile which utilizes this helper pack, and I've noticed that it works fine on Ruby 2.7, but when upgrading to Ruby 3.0 I receive the following error:

```
[2] pry(#<Inspec::Profile>)> e
=> #<ArgumentError: wrong number of arguments (given 1, expected 0)>
[3] pry(#<Inspec::Profile>)> e.backtrace
=> ["libraries/iam_bindings_cache.rb:31:in `initialize'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/resource.rb:127:in `block in initialize'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/resource.rb:60:in `supersuper_initialize'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/resource.rb:125:in `initialize'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/profile_context.rb:256:in `new'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/profile_context.rb:256:in `block (2 levels) in add_registry_methods'",
 "./inspec-gcp-cis-benchmark/controls/1.01-iam.rb:23:in `load_with_context'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/profile_context.rb:171:in `instance_eval'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/profile_context.rb:171:in `load_with_context'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/profile_context.rb:155:in `load_control_file'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/profile.rb:231:in `block in collect_tests'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/profile.rb:226:in `each'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/profile.rb:226:in `collect_tests'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/runner.rb:121:in `block in load'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/runner.rb:102:in `each'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/runner.rb:102:in `load'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/runner.rb:153:in `run'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/inspec-core-5.17.4/lib/inspec/cli.rb:313:in `exec'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'",
 "/Users/rbclark/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'",
```

This manifests itself on the top level as 

```
[2022-06-17T17:25:57-04:00] ERROR: Failed to load profile inspec-gcp-cis-benchmark: Failed to load source for controls/1.01-iam.rb: wrong number of arguments (given 1, expected 0)
```

I assume this has to do with changes in positional arguments between Ruby 2.7 and 3.0 however I've so far been unable to track down exactly how they need to be restructured in order to function properly.

**Comment by rbclark** [comment]
I did some more digging on this and found the issue was not actually Ruby 3.0 but rather InSpec not handling parameters properly with Ruby 3.0. I have put up a PR on InSpec which fixes this problem: https://github.com/inspec/inspec/pull/6155
